### ISSUE TITLE
Crash when a field is nil

### ISSUE THREAD

**Issue by kamilash** [NeowayLabs/jsondiff#2]

**Comment by katcipis** [comment]
Did not get it, which field ? where ? what? :-)

**Comment by kamilash** [comment]
We are not handling when a field in the JSON comes with the value nil.

**Comment by katcipis** [comment]
AFAIK JSON does not have nil values o.O. @kamilash you mean when the field is absent ?

**Comment by kamilash** [comment]
yes =)
